<?php
// $Id: xoops_version.php,v 1.1 2006/03/27 16:36:06 mikhail Exp $
//  ------------------------------------------------------------------------ //
//                No-Ah - PHP Content Architecture Stem                      //
//                    Copyright (c) 2004 KERKNESS.C                          //
//                       <http://noah.tetrasi.com>                          //
//                          A XOOPS.org Module                               //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
// Author: Ryan Mayberry AKA (fatman / kerkness)                             //
// URL: http://noah.tetrasi.com/                                             //
// Thanks: To everyone at xoops.org, dev,xoops and all No-Ah developers      //
// Project: The No-Ah Project                                                //
// ------------------------------------------------------------------------- //

$modversion['name'] = _MI_NA_NAME;
$modversion['version'] = '0.87';
$modversion['description'] = _MI_NA_DESC;
$modversion['credits'] = 'special thanks to xoops dev team';
$modversion['author'] = 'fatman';
$modversion['license'] = 'GNU';
$modversion['official'] = 0;
$modversion['image'] = 'images/na_slogo.png';
$modversion['dirname'] = 'noah';

// Admin
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Menu
$modversion['hasMain'] = 1;

// Search
$modversion['hasSearch'] = 0;
$modversion['search']['file'] = '';
$modversion['search']['func'] = '';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix! Prefix auto added on install of mod
$modversion['sqlfile']['mysql'] = 'sql/no-ah_db_0.8.7.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'noah_sysgroup';
$modversion['tables'][1] = 'noah_sysfield';
$modversion['tables'][2] = 'noah_page';
$modversion['tables'][3] = 'noah_pref';
$modversion['tables'][4] = 'noah_prefvalue';
$modversion['tables'][5] = 'noah_sfilter';
$modversion['tables'][6] = 'noah_ufilter';
$modversion['tables'][7] = 'noah_sitelist';
$modversion['tables'][8] = 'noah_sitevalue';
$modversion['tables'][9] = 'noah_syslist';
$modversion['tables'][10] = 'noah_sysvalue';
$modversion['tables'][11] = 'noah_relation';
$modversion['tables'][12] = 'noah_changelog';

// Module Templates
// List any template subfolders you have to the following array
// Leave first value blank for indexing root template folder
// example -> $folders = array('', 'pages/', 'group_details/', 'form/' );
$folders = ['', 'admin/', 'list/', 'item/', 'form/', 'page/'];

// Set the root path to the template folder
$templatedir = XOOPS_ROOT_PATH . '/modules/' . $modversion['dirname'] . '/templates/';

$files = [];

foreach ($folders as $folder) {
    $dir = opendir($templatedir . $folder);

    while (false !== ($file = readdir($dir))) {
        if (!preg_match('/^[.]{1,2}$/', $file)) {
            if (false !== strpos($file, "html")) {
                if ('cvs' != mb_strtolower($file) && !is_dir($file)) {
                    $files[] = $folder . $file;
                }
            }
        }
    }

    sort($files);

    closedir($dir);
}

for ($i = 0, $iMax = count($files); $i < $iMax; $i++) {
    $modversion['templates'][$i]['file'] = $files[$i];

    $modversion['templates'][$i]['description'] = '';
}

// NoAhBlocks
$modversion['blocks'][1]['file'] = 'noah_block.php';
$modversion['blocks'][1]['name'] = _MI_NA_BLOCK_MENU_NAME;
$modversion['blocks'][1]['description'] = _MI_NA_BLOCK_MENU_DESC;
$modversion['blocks'][1]['show_func'] = 'NoAhMenuBlock';
$modversion['blocks'][1]['template'] = 'menu_block.html';
